# -*- coding: utf-8 -*-

{
    'name': 'Selsela OpenHRMS Core',
    'version': '17.0.1.0.0',
    'category': 'Generic Modules/Human Resources',
    'summary': """Open HRMS Suit: It brings all Open HRMS modules""",
    'description': """Openhrms, Main module of Open HRMS, It brings all others 
    into a single module, Payroll, Payroll Accounting,Expense, Dashboard, 
    Employees, Employee Document, Resignation, Salary Advance, Loan Management,
    Gratuity, Service Request, Gosi, WPS Report, Reminder, Multi Company, 
    Shift Management, Employee History, Branch Transfer, Employee Appraisal,
    Biometric Device, Announcements, Insurance Management, Vacation Management,
    Employee Appreciations, Asset Custody, Employee Checklist, Entry and Exit 
    Checklist, Disciplinary Actions, openhrms, OpenHRMS, hrms, Attrition Rate, 
    Document Expiry, Visa Expiry, Law Suit Management, Employee, 
    Employee Training""",
    'author': "Selsela",
    'company': 'Selsela',
    'maintainer': 'Selsela',
    'website': "",
    'depends': ['web',
                'hr',
                'hr_payroll_account',
                'hr_gamification',
                'selsela_hr_employee_updation',
                'hr_recruitment',
                'hr_attendance',
                'hr_holidays',
                'hr_payroll',
                'hr_expense',
                'selsela_hr_leave_request_aliasing',
                'hr_timesheet',
                'selsela_oh_employee_creation_from_user',
                'selsela_employee_documents_expiry',
                'selsela_hr_multi_company',
                'selsela_loan_accounting',
                'selsela_ohrms_salary_advance',
                'selsela_hr_reward_warning',
                'selsela_hrms_dashboard',
                'selsela_hr_reminder',
                'selsela_employee_background',
                'selsela_employee_check_list',
                'selsela_hr_custody',
                'selsela_hr_employee_transfer',
                'selsela_hr_holidays_approval',
                'selsela_hr_resignation',
                'selsela_ohrms_loan',
                'selsela_ohrms_service_request',
                'selsela_saudi_gosi'

                ],
    'images': ['static/description/icon.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': True,
}
